services:
  postgres:
    image: postgres:16
    container_name: meditourism_postgres
    restart: always
    environment:
      POSTGRES_USER: meditourism
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: meditourism
    ports:
      - "5432:5432"
